<a href="https://colab.research.google.com/github/LuigiFalcade13/fatec_PLN_Codes/blob/main/Aula_5_Representa%C3%A7%C3%A3o_de_texto.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Luigi Falcade**

# Aula 5 - Representação de texto
## Exemplo 1 - Implementando o BoW

In [1]:
# importação das ferramentas a serem utilizadas
from sklearn.feature_extraction.text import CountVectorizer

# criando um documento com vários textos
documentos = [
    "gato e cachorro",
    "gato brinca com cachorro",
    "gato e rato"
]

vectorizer = CountVectorizer()

X = vectorizer.fit_transform(documentos)
  # fit >> cria uma lista com cada palavra que existe no texto
  # transform >> transforma as palavras em um vetor

print("Matriz BoW: ", X.toarray())

print(f"Vocabulário: {vectorizer.vocabulary_}")

Matriz BoW:  [[0 1 0 1 0]
 [1 1 1 1 0]
 [0 0 0 1 1]]
Vocabulário: {'gato': 3, 'cachorro': 1, 'brinca': 0, 'com': 2, 'rato': 4}


print(f"Vocabulário: {vectorizer.vocabulary_}")
O ChatGPT disse:
ChatGPT
O código utiliza a ferramenta CountVectorizer da biblioteca sklearn para criar uma Matriz de Frequência de Termos (Bag of Words - BoW) a partir de uma lista de documentos de texto. Primeiramente, ele cria uma lista de documentos com algumas frases. Em seguida, o CountVectorizer é utilizado para aprender o vocabulário dos documentos com o método fit_transform, que cria uma matriz em que cada linha representa um documento e cada coluna uma palavra única do vocabulário. O valor em cada célula da matriz indica quantas vezes a palavra aparece no respectivo documento. Por fim, o código imprime a matriz gerada e o vocabulário, ou seja, as palavras que compõem o texto. Isso é útil para representar textos de forma numérica, facilitando a análise em modelos de aprendizado de máquina.

## Exemplo 2 - Implementando o BOW junto com TF-IDF

In [2]:
# importação das ferramentas que serão utilizadas
from sklearn.feature_extraction.text import CountVectorizer #BoW
from sklearn.feature_extraction.text import TfidfVectorizer # TF-IDF
  # Term Frequency - Inverse Document Frequency >>> frequência ponderada

documentos = [
    "O cachorro gosta de passear no parque",
    "O gato dorme no sofá o dia todo",
    "Cachorros e gatos podem ser bons amigos"
]

# Vetorização pelo BoW
vectorizer_bow = CountVectorizer() # instância da ferramenta
X_bow = vectorizer_bow.fit_transform(documentos) # vetorização do texto

# impressão do vetor e da matriz
print(f"Vocabulário BoW: {vectorizer_bow.vocabulary_}")
print("Matrix BoW:")
print(X_bow.toarray())

# Vetorização TF-IDF
vectorizer_tfidf = TfidfVectorizer() # instânciação da classe
X_tfidf = vectorizer_tfidf.fit_transform(documentos) # vetorização
  # fit
  # transform

#impressão dos vetores com frequência ponderada
print(f"\nVocabulário TF-IDF: {vectorizer_tfidf.vocabulary_}")
print("Matriz TF-IDF")
print(X_tfidf.toarray())

Vocabulário BoW: {'cachorro': 2, 'gosta': 9, 'de': 4, 'passear': 12, 'no': 10, 'parque': 11, 'gato': 7, 'dorme': 6, 'sofá': 15, 'dia': 5, 'todo': 16, 'cachorros': 3, 'gatos': 8, 'podem': 13, 'ser': 14, 'bons': 1, 'amigos': 0}
Matrix BoW:
[[0 0 1 0 1 0 0 0 0 1 1 1 1 0 0 0 0]
 [0 0 0 0 0 1 1 1 0 0 1 0 0 0 0 1 1]
 [1 1 0 1 0 0 0 0 1 0 0 0 0 1 1 0 0]]

Vocabulário TF-IDF: {'cachorro': 2, 'gosta': 9, 'de': 4, 'passear': 12, 'no': 10, 'parque': 11, 'gato': 7, 'dorme': 6, 'sofá': 15, 'dia': 5, 'todo': 16, 'cachorros': 3, 'gatos': 8, 'podem': 13, 'ser': 14, 'bons': 1, 'amigos': 0}
Matriz TF-IDF
[[0.         0.         0.42339448 0.         0.42339448 0.
  0.         0.         0.         0.42339448 0.32200242 0.42339448
  0.42339448 0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.42339448
  0.42339448 0.42339448 0.         0.         0.32200242 0.
  0.         0.         0.         0.42339448 0.42339448]
 [0.40824829 0.40824829 0.        

O código utiliza duas técnicas para representar textos numericamente: BoW (Bag of Words) e TF-IDF. Com BoW, o texto é transformado em uma matriz de frequências das palavras. Já com TF-IDF, as palavras são ponderadas com base na frequência nos documentos e na raridade no conjunto, destacando palavras mais informativas. Ambas as técnicas são usadas para análise e modelagem de texto em PLN.

## Exemplo 3 - Aula 4 e aula 5
Exemplo de pré processamento e representação de texto com:
*   Limpeza de dados: removendo caracteres indesejados e normalizando o texto.
*   Tokenização: dividindo o texto em palavras individuais.
*   Remoção de StopWords:eliminando palavras comuns que não carregam significado semântico importante.
*   Lematização: reduzindo as palavras à sua forma base.
*   Representação de texto: convertendo o texto processado em uma matriz numérica usando o modelo Bag of Words.



In [5]:

# Importação das bibliotecas necessárias
import nltk
import re
from nltk.corpus import stopwords  # Para acessar as stopwords
from nltk.tokenize import word_tokenize  # Para realizar a tokenização das palavras
from nltk.stem import WordNetLemmatizer  # Para lemmatização (redução das palavras à sua forma base)
from sklearn.feature_extraction.text import CountVectorizer  # Para a vetorização do texto (Bag of Words)

# Download dos recursos do NLTK (se necessário)
nltk.download('punkt_tab')  # Tokenizador
nltk.download('stopwords')  # Stopwords em vários idiomas
nltk.download('wordnet')  # Banco de dados de lematização
nltk.download('omw-1.4')  # WordNet Open Multilingual Wordnet

# Lista de documentos de exemplo
documentos = [
    "Os cachorros são animais muito amigáveis e leais!",
    "Eu gosto de gatos porque eles são independentes e fofos.",
    "Cachorros e gatos podem ser ótimos animais de estimação."
]

# Instanciando o lematizador e definindo o conjunto de stopwords
lemmatizer = WordNetLemmatizer()  # Lematizador para reduzir palavras à sua forma base
stop_words = set(stopwords.words("portuguese"))  # Conjunto de palavras irrelevantes no português

# Função que realiza o pré-processamento do texto
def preprocessar_texto(texto):
    # Limpeza: Remove caracteres não alfabéticos e símbolos, mantendo apenas letras e espaços
    texto = re.sub(r'[^a-zA-Zá-ÿ\s]','', texto)

    # Tokenização: Quebra o texto em palavras
    tokens_tudo = word_tokenize(texto.lower())  # Converte o texto para minúsculo antes da tokenização

    # Remoção de stopwords: Filtra palavras irrelevantes
    tokens = [palavra for palavra in tokens_tudo if palavra not in stop_words]

    # Lematização: Reduz as palavras às suas formas base (ex: "cachorros" -> "cachorro")
    tokens_lema = [lemmatizer.lemmatize(palavra) for palavra in tokens]

    # Retorna o texto processado como uma string
    return ' '.join(tokens_lema)

# Aplica o pré-processamento a todos os documentos
documentos_processados = [preprocessar_texto(doc) for doc in documentos]

# Exibe os documentos após o pré-processamento
print('documentos Pré-processados:')
for i, doc in enumerate(documentos_processados):
    print(f"Documento {i + 1}: {doc}")

# Vetorização usando o modelo Bag of Words (BoW)
vectorizer = CountVectorizer()  # Instancia o CountVectorizer
X_bow = vectorizer.fit_transform(documentos_processados)  # Aplica o vetor de contagem nos documentos

# Exibe o vocabulário gerado (palavras mapeadas para índices)
print("\nVocabulário BoW:", vectorizer.vocabulary_)

# Exibe a matriz BoW (matriz de contagem das palavras)
print("Matriz BoW:")
print(X_bow.toarray())

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


documentos Pré-processados:
Documento 1: cachorros animais amigáveis leais
Documento 2: gosto gatos porque independentes fofos
Documento 3: cachorros gatos podem ótimos animais estimação

Vocabulário BoW: {'cachorros': 2, 'animais': 1, 'amigáveis': 0, 'leais': 8, 'gosto': 6, 'gatos': 5, 'porque': 10, 'independentes': 7, 'fofos': 4, 'podem': 9, 'ótimos': 11, 'estimação': 3}
Matriz BoW:
[[1 1 1 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 1 1 1 1 0 0 1 0]
 [0 1 1 1 0 1 0 0 0 1 0 1]]
